name: Feature Branch Build On Stable With Src Dependencies ( links, byteserde )
on:
  push:
     branches:
      - '*'
      - '!release*'
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out links current branch
        uses: actions/checkout@v3 
        with:
          path: soupbintcp
      - name: Check out byteserde/performance_v5
        uses: actions/checkout@v3 
        with:
          repository: 'softstream-link/byteserde'
          ref: 'performance_v5'  # TODO change branch
          path: byteserde
      - name: Check out links/ouch
        uses: actions/checkout@v3 
        with:
          repository: 'softstream-link/links'
          ref: 'ouch'  # TODO change branch
          path: links
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - uses: taiki-e/install-action@nextest
      - name: Testing 
        run: |
          cd soupbintcp
          cargo nextest run --all-features # --success-output final
          cargo nextest run --examples # --success-output final
          cargo test --doc #  NOTE: docs are not supported by nextest
          cargo doc --all-features # TODO how to fail on warnings?
      - name: Benchmarking
        run: |
          pushd soupbintcp
          cargo bench --all-features
      - name: Clippy Deny Warnings
        run: |
          pushd soupbintcp
          cargo clippy --all-features -- --deny warnings
      - name: Publish Dry Run
        run: |
          pushd soupbintcp
          pushd model && cargo publish --dry-run

