name: Push Test Build
on:
  pull_request:
    branches:
      - '*'
      - '!release*'
      - '!master'
  push:
      branches:
        - '*'
        - '!release*'
        - '!master'

jobs:
  test-matrix:
    uses: softstream-link/workflows/.github/workflows/rust-test-matrix-toolchain-os.yml@v1
    with:
      fail-fast: false
  clippy:
    uses: softstream-link/workflows/.github/workflows/rust-clippy-toolchain.yml@v1
  bench-matrix:
    uses: softstream-link/workflows/.github/workflows/rust-bench-matrix-toolchain-os.yml@v1
    with:
      fail-fast: false
  